# Generated by Django 4.2.6 on 2024-05-27 17:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Recetario', '0002_alter_receta_imagen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receta',
            new_name='Post',
        ),
    ]
